### ISSUE TITLE
406 Error even on successful purchases on live app

### ISSUE THREAD

**Issue by ehakan** [adjust/unity_purchase_sdk#14]
### Issue:

We've been encountering 406 errors for almost a month now, can't figure out what is going wrong. All the purchases are successfully processed by Google and Apple, registered to our clients, but sending the event adjust gives us 406 errors. When looking at our API consoles, no adjust usage is reported but the Adjust tokens seem ok.

We've tested the IAP's both on live store versions (with real credit cards) and on Testflight, Internal Beta (with testing methods).

### Code:

```csharp
        public PurchaseProcessingResult ProcessPurchase(PurchaseEventArgs args)
        {
            var purchasableItem = PurchasableItemManager.Instance.GetPurchasableItem(args.purchasedProduct.definition.id);

            if (purchasableItem == null)
            {
                Debug.Log($"ProcessPurchase: FAIL. Unrecognized product: '{args.purchasedProduct.definition.id}'");
                return PurchaseProcessingResult.Complete;
            }
            
            PurchasableItemManager.Instance.eventManager.FirePurchaseEvent(purchasableItem);
            purchasableItem.OnPurchase();
            
            // arguments of PurchaseEventArgs are passed down to AdjustPurchaseListener
            PurchasableItemManager.Instance.eventManager.FirePostPurchaseEvent(args.purchasedProduct.metadata.localizedPrice,
                args.purchasedProduct.metadata.isoCurrencyCode,
                args.purchasedProduct.transactionID,
                args.purchasedProduct.receipt,
                args.purchasedProduct.definition.id);
            
            return PurchaseProcessingResult.Complete;
        }
```

```csharp
        public void TrackPurchase(decimal price, string currency, string transactionId, string receipt, string definitionId)
        {
            adjustCurrency = currency;
            adjustPrice = price;
            adjustTransactionId = transactionId;
#if UNITY_IOS && !UNITY_EDITOR
            AdjustPurchase.VerifyPurchaseiOS(receipt, transactionId, definitionId, VerificationInfoDelegate);
#elif UNITY_ANDROID && !UNITY_EDITOR
            AdjustPurchase.VerifyPurchaseAndroid(definitionId, receipt, SystemInfo.deviceUniqueIdentifier, VerificationInfoDelegate);
#endif
        }

        private void VerificationInfoDelegate(ADJPVerificationInfo verificationInfo)
        {
            var finalToken = "";
            if (verificationInfo.VerificationState == ADJPVerificationState.ADJPVerificationStatePassed)
            {
                if (adjustToken != null && adjustPrice != 0 && adjustCurrency != null)
                {
                    finalToken = adjustToken;
                    AdjustEvent adjustEvent = new AdjustEvent(adjustToken);
                    adjustEvent.setRevenue((double) adjustPrice, adjustCurrency);
                    adjustEvent.setTransactionId(adjustTransactionId);
                    com.adjust.sdk.Adjust.trackEvent(adjustEvent);
                }

            adjustToken = null;
            adjustPrice = 0;
            adjustCurrency = null;
            adjustTransactionId = null;

            Debug.LogError("Verification info arrived to unity callback!");
            Debug.LogError("Message: " + verificationInfo.Message);
            Debug.LogError("Status code: " + verificationInfo.StatusCode);
            Debug.LogError("Verification state: " + verificationInfo.VerificationState);
            Debug.LogError("Sent Token: " + finalToken);
        }

```

 ### Logs:

(Sorry for the messy log format)

![log1](https://user-images.githubusercontent.com/20271015/92240605-8ecd2b00-eec5-11ea-8912-05c05729d457.png)
![log2](https://user-images.githubusercontent.com/20271015/92240613-9096ee80-eec5-11ea-9c1a-da812c21b0fb.png)
![log3](https://user-images.githubusercontent.com/20271015/92240617-92f94880-eec5-11ea-9890-a83e9fbe7ffe.png)

**Comment by melih-veloxia** [comment]
adjust/unity_sdk#187

**Comment by 2beens** [comment]
@ehakan @ugi 
OK, just checked the logs. So, from `all September`, all invalid purchases made by your App `al97a6x1hfk0` have the following reasons given by apple and google:
 - iTunes `Receipt Malformed`
 - GooglePlay `Purchase not found` 

This tells me that the problem comes from the receipt you are using to verify, maybe it is not formed properly. 
Hope this gives you some hints on what may be wrong.

**Comment by ugi** [comment]
@ehakan Which IAP library are you using? Is it **UnityIAP** or something else?

**Comment by ehakan** [comment]
It's UnityIAP (v2.0.6). Receipt information comes directly from class `PurchaseEventArgs` of namespace `UnityEngine.Purchasing`.

Here is what we receive as a receipt.

```json
{"Store":"GooglePlay","TransactionID":"GPA.3346-7960-8294-66105","Payload":"{\"json\":\"{\\\"orderId\\\":\\\"GPA.3346-7960-8294-66105\\\",\\\"packageName\\\":\\\"com.veloxia.spacecolonyidle\\\",\\\"productId\\\":\\\"houseofdiamonds\\\",\\\"purchaseTime\\\":1599467242519,\\\"purchaseState\\\":0,\\\"developerPayload\\\":\\\"{\\\\\\\"developerPayload\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"is_free_trial\\\\\\\":false,\\\\\\\"has_introductory_price_trial\\\\\\\":false,\\\\\\\"is_updated\\\\\\\":false,\\\\\\\"accountId\\\\\\\":\\\\\\\"\\\\\\\"}\\\",\\\"purchaseToken\\\":\\\"<PURCHASETOKEN>\\\"}\",\"signature\":\"<SIGNATURE>\",\"skuDetails\":\"{\\\"skuDetailsToken\\\":\\\"<SKUDETAILSTOKEN>\\\",\\\"productId\\\":\\\"houseofdiamonds\\\",\\\"type\\\":\\\"inapp\\\",\\\"price\\\":\\\"TRY 124.99\\\",\\\"price_amount_micros\\\":124990000,\\\"price_currency_code\\\":\\\"TRY\\\",\\\"title\\\":\\\"House of Gems (Space Colony: Idle)\\\",\\\"description\\\":\\\"100.000 Gems\\\"}\",\"isPurchaseHistorySupported\":true}"}
```

Parsing the JSON in javascript yields valid JSON.

**Comment by 2beens** [comment]
Google response specifies `Purchase not found`, so the receipt might have a good structure, but it's IDs are maybe wrong or it does not exist. Not sure.

**Comment by ehakan** [comment]
We've double checked our API access keys, service accounts and the Financing permission required for Adjust to function. It seems fine setup-wise.

![serviceaccs](https://user-images.githubusercontent.com/20271015/92412176-9ace1c80-f153-11ea-83e3-45040bcb32e7.png)

But the google services panel shows a very low usage for the service account.

**Comment by Handeyilmaz** [comment]
Hello @ehakan , In Google Play could you please check if this was set up correctly:
itemSku                   // Unique order ID (SKU) (https://developer.android.com/reference/com/android/billingclient/api/SkuDetails#getsku)
itemToken               // A token that uniquely identifies a purchase (https://developer.android.com/reference/com/android/billingclient/api/Purchase#getpurchasetoken)
developerPayload  // A developer-specified string that contains supplemental information about an order
callback                  // Callback method which will process the verification response

Also in iOS: [](https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store)
receipt                // App receipt of NSData type
transaction         // Finished transaction object of SKPaymentTransaction type
productId           // Your purchased product identifier of NSString type
responseBlock   // Callback method which will process the verification response

Additionally, could you make a test from the Terminal/any environment that will directly send a request to the Sore API for the purchase validation? (we can see if the Store will validate the purchase)

**Comment by ugi** [comment]
Hi @ehakan 

I am not sure your code for extracting necessary information from UnityIAP JSON is correct. This is example of how it should be done, so maybe try giving that a shot and let us know if it worked for you:

```cs
var transactionID = purchaseEventArgs.purchasedProduct.transactionID;
var productID = purchaseEventArgs.purchasedProduct.definition.id;
var receiptDict = (Dictionary<string, object>)MiniJson.JsonDecode(purchaseEventArgs.purchasedProduct.receipt);
var payload = (null != receiptDict && receiptDict.ContainsKey("Payload")) ? (string)receiptDict["Payload"] : "";


#if UNITY_IOS
    AdjustPurchase.VerifyPurchaseiOS(payload, transactionID, productID, verificationCb);
#elif UNITY_ANDROID
    var jsonDetailsDict = (!string.IsNullOrEmpty(payload)) ? (Dictionary<string, object>)MiniJson.JsonDecode(payload) : null;
    var json = (jsonDetailsDict != null && jsonDetailsDict.ContainsKey("json")) ? (string)jsonDetailsDict["json"] : "";
    var gpDetailsDict = (!string.IsNullOrEmpty(json)) ? (Dictionary<string, object>)MiniJson.JsonDecode(json) : null;
    var purchaseToken = (null != gpDetailsDict && gpDetailsDict.ContainsKey("purchaseToken")) ? (string)gpDetailsDict["purchaseToken"] : "";

    AdjustPurchase.VerifyPurchaseAndroid(productID, purchaseToken, "", verificationCb);
#endif
```

**Comment by Handeyilmaz** [comment]
Hi @ehakan , do you have any questions?

**Comment by ehakan** [comment]
Hello again, sorry for the late reply. We've exposed the purchaseEventArgs to the functions directly and used used ugi's code. It worked on both platforms so thanks for the help!
