### ISSUE TITLE
ADJPVerificationState.ADJPVerificationStatePassed

### ISSUE THREAD

**Issue by dgJero** [adjust/unity_purchase_sdk#7]
hi there,

our revenue tracking tracks the unverified purchases even though we've implemented the verification.

listens to prime31's Storekit

```
void purchaseSuccessfulEvent(StoreKitTransaction transaction) {
 AdjustPurchase.VerifyPurchaseiOS(transaction.base64EncodedTransactionReceipt, transaction.transactionIdentifier, transaction.productIdentifier, VerificationInfoDelegate);
}

private void VerificationInfoDelegate(ADJPVerificationInfo verificationInfo) {
 Debug.Log("Verification info arrived to unity callback!");
 Debug.Log("Message: " + verificationInfo.Message);
 Debug.Log("Status code: " + verificationInfo.StatusCode);
 Debug.Log("Verification state: " + verificationInfo.VerificationState);
 AdjustEvent adjEvent;
 switch (verificationInfo.VerificationState) {
  case ADJPVerificationState.ADJPVerificationStatePassed:
   adjEvent = new AdjustEvent("<event token 1>");
   adjEvent.setRevenue(revenue, "USD");
   break;
  case ADJPVerificationState.ADJPVerificationStateNotVerified:
   adjEvent = new AdjustEvent("<event token 2>");
   adjEvent.setRevenue(revenue, "USD");
   break;
  default:
   adjEvent = new AdjustEvent("<event token 3>");
   adjEvent.setRevenue(revenue, "USD");
   break;
 }
 adjEvent.setTransactionId(microTrans.transactionIdentifier);
 Adjust.trackEvent(adjEvent);
 revenue = 0;
}
```
did I miss something?

attached is logs on xcode
[purchaseLogs.pdf](https://github.com/adjust/unity_purchase_sdk/files/574640/purchaseLogs.pdf)

**Comment by uerceg** [comment]
Hi @dgJero 

From logs, I see that you have got `ADJPVerificationStatePassed` and status code `200` for this sandbox purchase you have done which pretty much means that this IAP was successfully validated. From your `VerificationInfoDelegate` method, this part of code got executed:

```
case ADJPVerificationState.ADJPVerificationStatePassed:
   adjEvent = new AdjustEvent("<event token 1>");
   adjEvent.setRevenue(revenue, "USD");
   break;
```

And event got tracked.

I didn't quite understand your question, to be honest. Would you like unverified purchases not to be tracked? Because if yes, from what I see in your code, you will track event regardless of what IAP verification state is. If you would like to track events only for certain verification states, then you need to adjust logic in your code when are you tracking events.

Ping me if you need any further assistance with this.

Cheers

**Comment by dgJero** [comment]
I see, though cross checking it to other dashboards/analytics, adjust includes the unverified purchases but not records on our unverified tracker.

is it working with just the basic plan on adjust? or do we need to subscribe to anti fraud?

**Comment by uerceg** [comment]
Hi @dgJero 

From the message I see in the logs, seems like you don't have purchase verification enabled for your account.

```
[AdjustPurchase]d: iTunes verification disabled for app
```

If PV is not enabled and you still try to use our PV SDK, we'll just report each one of the purchases as valid one + indicate this message in the answer.

I am not able to provide you with any helpful information in terms of activating this feature on your account, etc. For those things, please contact your AM or simply write an email to our support: support@adjust.com

If you have any other doubts and questions related to the SDK and coding part, feel free to ask. :)

Cheers

**Comment by uerceg** [comment]
Hi @dgJero 

Any progress on this issue?

Cheers

**Comment by dgJero** [comment]
Hello again,

We didn't continue with this.

Sorry and thank you for your time.
